/*
 * remote procedure call - distributed system

 * Modify the program described in Assignment 3 in such a way that the two programs can be run on different machines using Remote Procedure Calls (RPC). Remote procedure calls allow programs to make procedure calls into remote programs running on a different machine across the network and are therefore fundamental in building a distributed system. The  receiver.c and the processor.c have the same functionality as described in Assignment 3 except that they should use remote procedure calls to communicate and achieve the same functionality. 
*/

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <rpc/rpc.h>
#include "msg.h"  /* msg.h generated by rpcgen */


/*SHARED_MEMORY PROGRAM will demonstate a rpc call*/
int main(int argc, char *argv[])
{
    CLIENT *cl;
    int *result;
    char *server;
    int flag;
    
    //Only support one parameter
    if (argc != 2)
    {
        printf("Usage: clinet hostname not appropriate!");
        exit(1);
    }
    
    //create client
    cl = clnt_create(argv[1], SHARED_MEMORY_PROG, SHARED_MEMORY_VERS, "tcp");
    if (cl == NULL) {
        clnt_pcreateerror(argv[1]);
        exit(1);
    }
    
    //get server
    server = argv[1];
    
    //if the line contains the secret code "C00L".
    //sends this information as parameter to SHARED_MEMORY program
    while(1)
    {
        //get alpha numeric strings as input from the user
        //one line at a time
        char *line;
        size_t len = 0;
        sleep(2);
        
        printf("Please input your command:\n");
        if((flag = getline(&line, &len, stdin)) == -1)
        {
            clnt_destroy(cl);
            exit(0);
        }
        
        //printf("%s %d", line, len);
        if(strcmp(line, "exit\n") == 0)
        {
            clnt_destroy(cl);
            exit(0);
        }
        
        
        //if the line contains the secret code "C00L", call the remote procedure msg on the server
        if(strstr(line, "C00L")!= NULL)
        {
            result = msg_1(&line, cl);
            
            if (result == (int *)NULL)//an error occurred while calling the remote procedure, exit
            {
                clnt_perror(cl, server);
                clnt_destroy(cl);
                exit(1);
            }
            //succesfully called remote procedure
            printf("Back from shared_memory\n");
            
            //server was unable to print our message into a file
            //result is 0
            if (*result != 1)
            {
                clnt_perror(cl,argv[1]);
                clnt_destroy(cl);
                exit(1);
            }
        }
    }
    
    clnt_destroy(cl);
    return 0;
}
